AuctionsTable: #logicalId for Resources
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AuctionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions: # this is an array
      - AttributeName: id # Dash specify the items in the array, attributeName and Type are objects
        AttributeType: S #string
    KeySchema:
      - AttributeName: id
        KeyType: HASH
